DROP DATABASE IF EXISTS MUSICSTORAGE;
CREATE DATABASE MUSICSTORAGE;

USE MUSICSTORAGE;

DROP USER IF EXISTS music@localhost;
CREATE USER music@'localhost' IDENTIFIED BY 'dawson123';
GRANT ALL ON MUSICSTORAGE.* TO music@'localhost';

FLUSH PRIVILEGES;